force-app/main/default/objects/SalesOrganization__c/SalesOrganization__c.object-meta.xml
<CustomObject>
    <description>Represents Sales Orgnaization information, typically derived from an ERP</description>
    <label>Sales Organization</label>
    <nameField>
        <label>Sales Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrganization__c/fields/SalesOrganizationName__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganizationName__c</fullName>
    <description>The selectable picklist to name the Sales Organization</description>
    <label>Sales Organization Name (picklist)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesOrganization</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrganization__c/fields/TimeSheetGeneration__c.field-meta.xml
<CustomField>
    <fullName>TimeSheetGeneration__c</fullName>
    <description>Defines how shall Time Sheets be generated for a Service Resource who belongs to this Sales Org.</description>
    <label>Time Sheet Generation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeSheetGeneration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganization__c</fullName>
    <formula>TEXT(RelatedRecord.SalesOrganization__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganization__c</fullName>
    <description>Refers to the Sales Org to which the user belongs to</description>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesOrganization</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/SalesOrganization.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <label>USA</label>
    </customValue>
    <customValue>
        <fullName>MX</fullName>
        <label>Mexico</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>France</label>
    </customValue>
    <description>Sales Organization names as picklists</description>
    <masterLabel>Sales Organization</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TimeSheetGeneration.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Weekly</fullName>
        <default>true</default>
        <label>Weekly</label>
    </customValue>
    <customValue>
        <fullName>Weekly with Month-End Closing</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <description>Defines what way should Time Sheet records be created</description>
    <masterLabel>Time Sheet Generation</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TimeSheetCreationBatch.cls
/*
 * Create Time Sheet records for the active Service Resources as a batch process
 * @version	1.1
 * @date        October 21st, 2024
 * @date		January 8th, 2025
 * @description	Ensure that month-end split weeks are split even if the month-end day is Saturday or Sunday
 */

public without sharing class TimeSheetCreationBatch implements Database.Batchable<sObject>, Database.Stateful {
	public Integer countRecords = 0; // Service Resource records count
	Integer weeksAhead = 12; // Defines how many full weeks ahead need Time Sheets to be generated
	Date allTimeSheetsEndDate; // The highest End Date till the batch Time Sheet records should generate

	public TimeSheetCreationBatch(Integer iWeeksAhead) {
		weeksAhead = iWeeksAhead;
	}

	public Database.QueryLocator start(Database.BatchableContext bc) {
		// check what is the next endDate ahead

		allTimeSheetsEndDate = TimeSheetUtils.getAllTimeSheetsEndDate(weeksAhead);
		// Also query the Service Resource User's SAP Sales Organization
		String queryString = 'select Id, Name, RelatedRecordId, RelatedRecord.SalesOrganization__c, ';
		queryString += '(select Id, StartDate, EndDate, OwnerId from TimeSheets Order by EndDate desc limit 6) ';
		queryString += 'from ServiceResource where isActive = true'; 
		return Database.getQueryLocator(queryString);
	}

	public void execute( Database.BatchableContext bc, List<ServiceResource> scope) {
		List<TimeSheet> toSaveTimeSheets = new List<TimeSheet>();
		// Get the Service Sales Organizations which belong to the SR users
		Set<String> salesOrgNames = new Set<String>();
		for (ServiceResource sr : scope) {
			salesOrgNames.add(sr.RelatedRecord.SalesOrganization__c);
		}
		List<SalesOrganization__c> salesOrgs = new List<SalesOrganization__c>(
		[
			SELECT Id, Name, TimeSheetGeneration__c, SalesOrganizationName__c
			FROM SalesOrganization__c
			WHERE SalesOrganizationName__c IN :salesOrgNames
		]);
		Map<String, String> soNametoTSGeneration = new Map<String, String>();
		for (SalesOrganization__c so : salesOrgs) {
			soNametoTSGeneration.put(
				so.SalesOrganizationName__c,
				so.TimeSheetGeneration__c
			);
		}

		for (ServiceResource sr : scope) {
			countRecords++;
			// Define the isMonthEndSplit value: weekly or weekly with month-end split
			Boolean isMonthEndSplit = true;

			if(sr.RelatedRecord.SalesOrganization__c == null){
				// The user's SalesOrganization is not filled in -> No Time Sheet to generate for the Service Resource
				continue;
			}

			if( sr.RelatedRecord.SalesOrganization__c != null &&
				soNametoTSGeneration.get( sr.RelatedRecord.SalesOrganization__c) == 'Weekly'){
				
					isMonthEndSplit = false;
			}
			if(soNametoTSGeneration.get( sr.RelatedRecord.SalesOrganization__c) == 'No'){
				// No TimeSheet generation for this Service Resource for this Service Sales Org
				continue;
			}
			// Create all Time sheets required for the particulare Service Resource
			List<TimeSheet> srToSaveTimeSheets = TimeSheetUtils.createTimeSheets(sr, isMonthEndSplit, weeksAhead);
			toSaveTimeSheets.addAll(srToSaveTimeSheets);
		}
		insert toSaveTimeSheets;
	}

	public void finish(Database.BatchableContext bc) {
		System.debug(
			'Batch ends. Total number of activeResources = ' + countRecords
		);
	}

}